# coding=utf-8
geo = [
        {"text":u"ÅLAND ISLANDS", "value":u"AX"},
        {"text":u"AFGHANISTAN", "value":u"AF"},
        {"text":u"ALBANIA", "value":u"AL"},
        {"text":u"ALGERIA", "value":u"DZ"},
        {"text":u"AMERICAN SAMOA", "value":u"AS"},
        {"text":u"ANDORRA", "value":u"AD"},
        {"text":u"ANGOLA", "value":u"AO"},
        {"text":u"ANGUILLA", "value":u"AI"},
        {"text":u"ANTARCTICA", "value":u"AQ"},
        {"text":u"ANTIGUA AND BARBUDA", "value":u"AG"},
        {"text":u"ARGENTINA", "value":u"AR"},
        {"text":u"ARMENIA", "value":u"AM"},
        {"text":u"ARUBA", "value":u"AW"},
        {"text":u"AUSTRALIA", "value":u"AU"},
        {"text":u"AUSTRIA", "value":u"AT"},
        {"text":u"AZERBAIJAN", "value":u"AZ"},
        {"text":u"BAHAMAS", "value":u"BS"},
        {"text":u"BAHRAIN", "value":u"BH"},
        {"text":u"BANGLADESH", "value":u"BD"},
        {"text":u"BARBADOS", "value":u"BB"},
        {"text":u"BELARUS", "value":u"BY"},
        {"text":u"BELGIUM", "value":u"BE"},
        {"text":u"BELIZE", "value":u"BZ"},
        {"text":u"BENIN", "value":u"BJ"},
        {"text":u"BERMUDA", "value":u"BM"},
        {"text":u"BHUTAN", "value":u"BT"},
        {"text":u"BOLIVIA", "value":u"BO"},
        {"text":u"BOSNIA AND HERZEGOWINA", "value":u"BA"},
        {"text":u"BOTSWANA", "value":u"BW"},
        {"text":u"BOUVET ISLAND", "value":u"BV"},
        {"text":u"BRAZIL", "value":u"BR"},
        {"text":u"BRITISH INDIAN OCEAN TERRITORY", "value":u"IO"},
        {"text":u"BRUNEI DARUSSALAM", "value":u"BN"},
        {"text":u"BULGARIA", "value":u"BG"},
        {"text":u"BURKINA FASO", "value":u"BF"},
        {"text":u"BURUNDI", "value":u"BI"},
        {"text":u"CAMBODIA", "value":u"KH"},
        {"text":u"CAMEROON", "value":u"CM"},
        {"text":u"CANADA", "value":u"CA"},
        {"text":u"CAPE VERDE", "value":u"CV"},
        {"text":u"CAYMAN ISLANDS", "value":u"KY"},
        {"text":u"CENTRAL AFRICAN REPUBLIC", "value":u"CF"},
        {"text":u"CHAD", "value":u"TD"},
        {"text":u"CHILE", "value":u"CL"},
        {"text":u"CHINA", "value":u"CN"},
        {"text":u"CHRISTMAS ISLAND", "value":u"CX"},
        {"text":u"COCOS (KEELING) ISLANDS", "value":u"CC"},
        {"text":u"COLOMBIA", "value":u"CO"},
        {"text":u"COMOROS", "value":u"KM"},
        {"text":u"CONGO, Democratic Republic of (was Zaire)", "value":u"CD"},
        {"text":u"CONGO, Republic of", "value":u"CG"},
        {"text":u"COOK ISLANDS", "value":u"CK"},
        {"text":u"COSTA RICA", "value":u"CR"},
        {"text":u"CÔTE D'IVOIRE", "value":u"CI"},
        {"text":u"CROATIA (local name: Hrvatska)", "value":u"HR"},
        {"text":u"CUBA", "value":u"CU"},
        {"text":u"CURAÇAO", "value":u"CW"},
        {"text":u"CYPRUS", "value":u"CY"},
        {"text":u"CZECH REPUBLIC", "value":u"CZ"},
        {"text":u"DENMARK", "value":u"DK"},
        {"text":u"DJIBOUTI", "value":u"DJ"},
        {"text":u"DOMINICA", "value":u"DM"},
        {"text":u"DOMINICAN REPUBLIC", "value":u"DO"},
        {"text":u"ECUADOR", "value":u"EC"},
        {"text":u"EGYPT", "value":u"EG"},
        {"text":u"EL SALVADOR", "value":u"SV"},
        {"text":u"EQUATORIAL GUINEA", "value":u"GQ"},
        {"text":u"ERITREA", "value":u"ER"},
        {"text":u"ESTONIA", "value":u"EE"},
        {"text":u"ETHIOPIA", "value":u"ET"},
        {"text":u"FALKLAND ISLANDS (MALVINAS)", "value":u"FK"},
        {"text":u"FAROE ISLANDS", "value":u"FO"},
        {"text":u"FIJI", "value":u"FJ"},
        {"text":u"FINLAND", "value":u"FI"},
        {"text":u"FRANCE", "value":u"FR"},
        {"text":u"FRENCH GUIANA", "value":u"GF"},
        {"text":u"FRENCH POLYNESIA", "value":u"PF"},
        {"text":u"FRENCH SOUTHERN TERRITORIES", "value":u"TF"},
        {"text":u"GABON", "value":u"GA"},
        {"text":u"GAMBIA", "value":u"GM"},
        {"text":u"GEORGIA", "value":u"GE"},
        {"text":u"GERMANY", "value":u"DE"},
        {"text":u"GHANA", "value":u"GH"},
        {"text":u"GIBRALTAR", "value":u"GI"},
        {"text":u"GREECE", "value":u"GR"},
        {"text":u"GREENLAND", "value":u"GL"},
        {"text":u"GRENADA", "value":u"GD"},
        {"text":u"GUADELOUPE", "value":u"GP"},
        {"text":u"GUAM", "value":u"GU"},
        {"text":u"GUATEMALA", "value":u"GT"},
        {"text":u"GUINEA", "value":u"GN"},
        {"text":u"GUINEA-BISSAU", "value":u"GW"},
        {"text":u"GUYANA", "value":u"GY"},
        {"text":u"HAITI", "value":u"HT"},
        {"text":u"HEARD AND MC DONALD ISLANDS", "value":u"HM"},
        {"text":u"HONDURAS", "value":u"HN"},
        {"text":u"HONG KONG", "value":u"HK"},
        {"text":u"HUNGARY", "value":u"HU"},
        {"text":u"ICELAND", "value":u"IS"},
        {"text":u"INDIA", "value":u"IN"},
        {"text":u"INDONESIA", "value":u"ID"},
        {"text":u"IRAN (ISLAMIC REPUBLIC OF)", "value":u"IR"},
        {"text":u"IRAQ", "value":u"IQ"},
        {"text":u"IRELAND", "value":u"IE"},
        {"text":u"ISRAEL", "value":u"IL"},
        {"text":u"ITALY", "value":u"IT"},
        {"text":u"JAMAICA", "value":u"JM"},
        {"text":u"JAPAN", "value":u"JP"},
        {"text":u"JORDAN", "value":u"JO"},
        {"text":u"KAZAKHSTAN", "value":u"KZ"},
        {"text":u"KENYA", "value":u"KE"},
        {"text":u"KIRIBATI", "value":u"KI"},
        {"text":u"KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF", "value":u"KP"},
        {"text":u"KOREA, REPUBLIC OF", "value":u"KR"},
        {"text":u"KUWAIT", "value":u"KW"},
        {"text":u"KYRGYZSTAN", "value":u"KG"},
        {"text":u"LAO PEOPLE'S DEMOCRATIC REPUBLIC", "value":u"LA"},
        {"text":u"LATVIA", "value":u"LV"},
        {"text":u"LEBANON", "value":u"LB"},
        {"text":u"LESOTHO", "value":u"LS"},
        {"text":u"LIBERIA", "value":u"LR"},
        {"text":u"LIBYAN ARAB JAMAHIRIYA", "value":u"LY"},
        {"text":u"LIECHTENSTEIN", "value":u"LI"},
        {"text":u"LITHUANIA", "value":u"LT"},
        {"text":u"LUXEMBOURG", "value":u"LU"},
        {"text":u"MACAU", "value":u"MO"},
        {"text":u"MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF", "value":u"MK"},
        {"text":u"MADAGASCAR", "value":u"MG"},
        {"text":u"MALAWI", "value":u"MW"},
        {"text":u"MALAYSIA", "value":u"MY"},
        {"text":u"MALDIVES", "value":u"MV"},
        {"text":u"MALI", "value":u"ML"},
        {"text":u"MALTA", "value":u"MT"},
        {"text":u"MARSHALL ISLANDS", "value":u"MH"},
        {"text":u"MARTINIQUE", "value":u"MQ"},
        {"text":u"MAURITANIA", "value":u"MR"},
        {"text":u"MAURITIUS", "value":u"MU"},
        {"text":u"MAYOTTE", "value":u"YT"},
        {"text":u"MEXICO", "value":u"MX"},
        {"text":u"MICRONESIA, FEDERATED STATES OF", "value":u"FM"},
        {"text":u"MOLDOVA, REPUBLIC OF", "value":u"MD"},
        {"text":u"MONACO", "value":u"MC"},
        {"text":u"MONGOLIA", "value":u"MN"},
        {"text":u"MONTSERRAT", "value":u"MS"},
        {"text":u"MOROCCO", "value":u"MA"},
        {"text":u"MOZAMBIQUE", "value":u"MZ"},
        {"text":u"MYANMAR", "value":u"MM"},
        {"text":u"NAMIBIA", "value":u"NA"},
        {"text":u"NAURU", "value":u"NR"},
        {"text":u"NEPAL", "value":u"NP"},
        {"text":u"NETHERLANDS", "value":u"NL"},
        {"text":u"NETHERLANDS ANTILLES", "value":u"AN"},
        {"text":u"NEW CALEDONIA", "value":u"NC"},
        {"text":u"NEW ZEALAND", "value":u"NZ"},
        {"text":u"NICARAGUA", "value":u"NI"},
        {"text":u"NIGER", "value":u"NE"},
        {"text":u"NIGERIA", "value":u"NG"},
        {"text":u"NIUE", "value":u"NU"},
        {"text":u"NORFOLK ISLAND", "value":u"NF"},
        {"text":u"NORTHERN MARIANA ISLANDS", "value":u"MP"},
        {"text":u"NORWAY", "value":u"NO"},
        {"text":u"OMAN", "value":u"OM"},
        {"text":u"PAKISTAN", "value":u"PK"},
        {"text":u"PALAU", "value":u"PW"},
        {"text":u"PALESTINIAN TERRITORY, Occupied", "value":u"PS"},
        {"text":u"PANAMA", "value":u"PA"},
        {"text":u"PAPUA NEW GUINEA", "value":u"PG"},
        {"text":u"PARAGUAY", "value":u"PY"},
        {"text":u"PERU", "value":u"PE"},
        {"text":u"PHILIPPINES", "value":u"PH"},
        {"text":u"PITCAIRN", "value":u"PN"},
        {"text":u"POLAND", "value":u"PL"},
        {"text":u"PORTUGAL", "value":u"PT"},
        {"text":u"PUERTO RICO", "value":u"PR"},
        {"text":u"QATAR", "value":u"QA"},
        {"text":u"RÉUNION", "value":u"RE"},
        {"text":u"ROMANIA", "value":u"RO"},
        {"text":u"RUSSIAN FEDERATION", "value":u"RU"},
        {"text":u"RWANDA", "value":u"RW"},
        {"text":u"SAINT HELENA", "value":u"SH"},
        {"text":u"SAINT KITTS AND NEVIS", "value":u"KN"},
        {"text":u"SAINT LUCIA", "value":u"LC"},
        {"text":u"SAINT PIERRE AND MIQUELON", "value":u"PM"},
        {"text":u"SAINT VINCENT AND THE GRENADINES", "value":u"VC"},
        {"text":u"SAMOA", "value":u"WS"},
        {"text":u"SAN MARINO", "value":u"SM"},
        {"text":u"SAO TOME AND PRINCIPE", "value":u"ST"},
        {"text":u"SAUDI ARABIA", "value":u"SA"},
        {"text":u"SENEGAL", "value":u"SN"},
        {"text":u"SERBIA AND MONTENEGRO", "value":u"CS"},
        {"text":u"SEYCHELLES", "value":u"SC"},
        {"text":u"SIERRA LEONE", "value":u"SL"},
        {"text":u"SINGAPORE", "value":u"SG"},
        {"text":u"SLOVAKIA", "value":u"SK"},
        {"text":u"SLOVENIA", "value":u"SI"},
        {"text":u"SOLOMON ISLANDS", "value":u"SB"},
        {"text":u"SOMALIA", "value":u"SO"},
        {"text":u"SOUTH AFRICA", "value":u"ZA"},
        {"text":u"SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS", "value":u"GS"},
        {"text":u"SPAIN", "value":u"ES"},
        {"text":u"SRI LANKA", "value":u"LK"},
        {"text":u"SUDAN", "value":u"SD"},
        {"text":u"SURINAME", "value":u"SR"},
        {"text":u"SVALBARD AND JAN MAYEN ISLANDS", "value":u"SJ"},
        {"text":u"SWAZILAND", "value":u"SZ"},
        {"text":u"SWEDEN", "value":u"SE"},
        {"text":u"SWITZERLAND", "value":u"CH"},
        {"text":u"SYRIAN ARAB REPUBLIC", "value":u"SY"},
        {"text":u"TAIWAN", "value":u"TW"},
        {"text":u"TAJIKISTAN", "value":u"TJ"},
        {"text":u"TANZANIA, UNITED REPUBLIC OF", "value":u"TZ"},
        {"text":u"THAILAND", "value":u"TH"},
        {"text":u"TIMOR-LESTE", "value":u"TL"},
        {"text":u"TOGO", "value":u"TG"},
        {"text":u"TOKELAU", "value":u"TK"},
        {"text":u"TONGA", "value":u"TO"},
        {"text":u"TRINIDAD AND TOBAGO", "value":u"TT"},
        {"text":u"TUNISIA", "value":u"TN"},
        {"text":u"TURKEY", "value":u"TR"},
        {"text":u"TURKMENISTAN", "value":u"TM"},
        {"text":u"TURKS AND CAICOS ISLANDS", "value":u"TC"},
        {"text":u"TUVALU", "value":u"TV"},
        {"text":u"UGANDA", "value":u"UG"},
        {"text":u"UKRAINE", "value":u"UA"},
        {"text":u"UNITED ARAB EMIRATES", "value":u"AE"},
        {"text":u"UNITED KINGDOM", "value":u"GB"},
        {"text":u"UNITED STATES", "value":u"US"},
        {"text":u"UNITED STATES MINOR OUTLYING ISLANDS", "value":u"UM"},
        {"text":u"URUGUAY", "value":u"UY"},
        {"text":u"UZBEKISTAN", "value":u"UZ"},
        {"text":u"VANUATU", "value":u"VU"},
        {"text":u"VATICAN CITY STATE (HOLY SEE)", "value":u"VA"},
        {"text":u"VENEZUELA", "value":u"VE"},
        {"text":u"VIET NAM", "value":u"VN"},
        {"text":u"VIRGIN ISLANDS (BRITISH)", "value":u"VG"},
        {"text":u"VIRGIN ISLANDS (U.S.)", "value":u"VI"},
        {"text":u"WALLIS AND FUTUNA ISLANDS", "value":u"WF"},
        {"text":u"WESTERN SAHARA", "value":u"EH"},
        {"text":u"YEMEN",    "value":u"YE"},
        {"text":u"ZAMBIA",   "value":u"ZM"},
        {"text":u"ZIMBABWE", "value":u"ZW"}
      ]
